version: "3.8"
services:
  php:
    container_name: php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    expose:
      - 9000
    volumes:
      - .:/usr/src/app
      - ./public:/usr/src/app/public
    depends_on:
      - mysql
    networks:
      - birimtahan

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
    - ./public:/usr/src/app/public
    ports:
      - 8000:80
    depends_on:
      - php
    environment:
      NGINX_FPM_HOST: php
      NGINX_ROOT: /usr/src/app/public
    networks:
      - birimtahan

  mysql:
    container_name: mysql
    image: mysql:8.0.20
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: birimtahan
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - birimtahan

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - birimtahan

volumes:
    db-data: ~

networks:
  birimtahan:
    name: birimtahan
